# Generated by Django 2.0 on 2019-02-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfoliopage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopage',
            name='designation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
