# Generated by Django 2.0 on 2019-02-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190225_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopage',
            name='age',
            field=models.DateField(blank=True, verbose_name='Date of Birth'),
        ),
    ]
