# Generated by Django 2.0 on 2019-02-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20190225_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='phoneno',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
