# Generated by Django 2.0 on 2019-02-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfoliopage_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopage',
            name='phoneno',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
