# Generated by Django 2.0 on 2019-02-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20190225_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='git_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
