# Generated by Django 2.0 on 2019-02-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20190225_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliopage',
            name='source',
        ),
    ]
