# Generated by Django 2.0 on 2019-02-25 20:04

from django.db import migrations, models
import wagtailmd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20190225_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='resume_content',
            field=wagtailmd.utils.MarkdownField(blank=True, verbose_name='Resume Content'),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='resume_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
