# Generated by Django 2.0 on 2019-02-26 14:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20190225_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='education',
            field=wagtail.core.fields.StreamField((('education', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(classname='full title')), ('university', wagtail.core.blocks.CharBlock(classname='full title')), ('year_passing', wagtail.core.blocks.CharBlock(classname='full title')), ('education_content', wagtail.core.blocks.CharBlock(classname='full title'))))),), blank=True, null=True),
        ),
    ]
