# Generated by Django 2.0 on 2019-03-12 19:35

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20190312_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='employment',
            field=wagtail.core.fields.StreamField((('employment', wagtail.core.blocks.StructBlock((('company_name', wagtail.core.blocks.CharBlock(classname='full title')), ('experience', wagtail.core.blocks.CharBlock(classname='full title')), ('designation', wagtail.core.blocks.CharBlock(classname='full title'))))),), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='employment_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
