# Generated by Django 2.0 on 2019-03-12 20:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20190312_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopage',
            name='project',
            field=wagtail.core.fields.StreamField((('project', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock(classname='full title')), ('description', wagtail.core.blocks.RichTextBlock()), ('menu_title', wagtail.core.blocks.CharBlock(classname='full title')), ('project_url', wagtail.core.blocks.CharBlock(classname='full title')), ('project_image', wagtail.images.blocks.ImageChooserBlock())))),), blank=True, null=True),
        ),
    ]
