# Generated by Django 2.0 on 2019-03-14 15:01

import datetime
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_auto_20190314_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Project date'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='project',
            field=wagtail.core.fields.StreamField((('project', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock(classname='full title')), ('description', wagtail.core.blocks.RichTextBlock()), ('menu_title', wagtail.core.blocks.CharBlock(classname='full title')), ('project_url', wagtail.core.blocks.URLBlock(classname='full title')), ('project_image', wagtail.images.blocks.ImageChooserBlock()), ('image_text', wagtail.core.blocks.CharBlock(classname='full title')), ('start_date', wagtail.core.blocks.CharBlock(classname='full title')), ('end_date', wagtail.core.blocks.CharBlock(classname='full title')), ('language', wagtail.core.blocks.StreamBlock((('skills', wagtail.core.blocks.CharBlock()),), icon='user'))))),), blank=True, null=True),
        ),
    ]
