# Generated by Django 2.0 on 2019-03-15 06:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_portfoliopage_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopage',
            name='testimonial',
            field=wagtail.core.fields.StreamField((('testimonial', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(classname='full title')), ('sub_title', wagtail.core.blocks.CharBlock(classname='full title')), ('content', wagtail.core.blocks.RichTextBlock(blank=True))))),), blank=True, null=True),
        ),
    ]
