# Generated by Django 2.0 on 2019-03-15 08:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_auto_20190315_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.core.fields.StreamField((('body', wagtail.core.blocks.RichTextBlock()),)),
        ),
    ]
