# Generated by Django 2.0 on 2019-03-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_auto_20190317_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlpage',
            name='copy_rights',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
